export const FETCH_POST_COMMENTS_INGROGRESS = 'FETCH_POST_COMMENTS_INGROGRESS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_FAILED = 'FETCH_POST_COMMENTS_FAILED';

export const DELETE_POST_COMMENT_SUCCESS = 'DELETE_POST_COMMENT_SUCCESS';
export const DELETE_POST_COMMENT_FAILED = 'DELETE_POST_COMMENT_FAILED';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';
