export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SIGN_OUT = 'SIGN_OUT';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_UNSUCCESS = 'UPDATE_USER_UNSUCCESS';
